name: "Gemini Datadog Responder"
description: "Queries Datadog for alerts and metrics, then uses Gemini to interpret and take repository actions"
author: "dortort"

inputs:
  datadog_api_key:
    description: "Datadog API key"
    required: true
  datadog_app_key:
    description: "Datadog application key"
    required: true
  query:
    description: "Datadog metrics query or monitor ID"
    required: true
  action:
    description: "Action to take: open_issue, comment_on_pr, or trigger_workflow"
    required: true
  gemini_api_key:
    description: "Google Gemini API key"
    required: true
  github_token:
    description: "GitHub token with repo write access"
    required: true
  model:
    description: "Gemini model to use"
    required: false
    default: "gemini-2.0-flash"

outputs:
  result:
    description: "The action result (issue number, comment URL, or workflow run ID)"

runs:
  using: "node20"
  main: "dist/index.js"
