name: "Gemini PR Review"
description: "Performs an automated code review on a pull request using Gemini"
author: "dortort"

inputs:
  pr_number:
    description: "The pull request number to review"
    required: true
  review_strictness:
    description: "Review strictness level: low, medium, or high"
    required: false
    default: "medium"
  gemini_api_key:
    description: "Google Gemini API key"
    required: true
  github_token:
    description: "GitHub token with repo write access"
    required: true
  model:
    description: "Gemini model to use"
    required: false
    default: "gemini-2.0-flash"

runs:
  using: "node20"
  main: "dist/index.js"
