import {
  generateContent,
  truncateText,
  getPullRequest,
  getFileContent,
  postComment,
  ActionContext,
} from "@gemini-actions/shared";
import { extractTestFilePaths } from "./parsers";

export interface TestFailureDiagnosisInputs {
  prNumber: number;
  testOutput: string;
}

export async function runTestFailureDiagnosis(
  ctx: ActionContext,
  inputs: TestFailureDiagnosisInputs,
): Promise<void> {
  const { octokit, owner, repo, model } = ctx;
  const { prNumber } = inputs;

  // Truncate very long test output to fit in the prompt
  const testOutput = truncateText(inputs.testOutput, 15000, "test output");

  // 1. Get PR details and diff
  const pr = await getPullRequest(octokit, owner, repo, prNumber);

  // 2. Extract failing test file names from the output
  const testFilePatterns = extractTestFilePaths(testOutput);

  // 3. Fetch failing test source code (if identifiable)
  const testSources: Record<string, string> = {};
  for (const testFile of testFilePatterns.slice(0, 5)) {
    try {
      const content = await getFileContent(
        octokit,
        owner,
        repo,
        testFile,
        pr.head.ref,
      );
      testSources[testFile] = content;
    } catch {
      // Skip files we can't read
    }
  }

  // 4. Send to Gemini for diagnosis
  const prompt = `You are a senior software engineer diagnosing test failures on a pull request.

**PR Title:** ${pr.title}
**PR Description:** ${pr.body ?? "No description."}

**PR Diff (changes made):**
\`\`\`diff
${truncateText(
  pr.files
    .map(
      (f) =>
        `--- ${f.filename} ---\n${f.patch ?? "(binary or no diff)"}`,
    )
    .join("\n\n"),
  15000,
  "PR diff",
)}
\`\`\`

**Test Output (failures):**
\`\`\`
${testOutput}
\`\`\`

${
  Object.keys(testSources).length > 0
    ? `**Failing Test Source Code:**
${Object.entries(testSources)
  .map(([path, content]) => `--- ${path} ---\n\`\`\`\n${truncateText(content, 5000, path)}\n\`\`\``)
  .join("\n\n")}`
    : ""
}

Provide a diagnosis that includes:

1. **Root Cause**: Explain the causal link between the PR changes and the test failures. What specific change caused what specific test to fail, and why?
2. **Affected Tests**: List each failing test and explain why it fails.
3. **Suggested Fix**: Provide specific, actionable fix suggestions. Include code snippets where helpful. Indicate whether the fix should be in the source code or the tests.

Format your response as clear, structured markdown.`;

  const diagnosis = await generateContent(model, prompt);

  // 5. Post the diagnosis as a comment
  const comment = `## Gemini Test Failure Diagnosis

${diagnosis}

---
*Analyzed ${pr.files.length} changed file(s) and ${testFilePatterns.length} test file(s) — Generated by [gemini-test-failure-diagnosis](https://github.com/dortort/gemini-actions)*`;

  await postComment(octokit, owner, repo, prNumber, comment);
}
