import {
  generateContent,
  truncateText,
  parseJsonResponse,
  getIssue,
  getFileContent,
  postComment,
  getDefaultBranch,
  getRepoTree,
  ActionContext,
} from "@gemini-actions/shared";
import { matchesAnyGlob } from "./globs";
import { buildFileSelectionPrompt, buildAnswerPrompt } from "./prompts";

export interface RepoQAInputs {
  issueNumber?: number;
  discussionId?: string;
  sourcePaths: string;
}

export async function runRepoQA(
  ctx: ActionContext,
  inputs: RepoQAInputs,
): Promise<void> {
  const { octokit, owner, repo, model } = ctx;

  if (!inputs.issueNumber && !inputs.discussionId) {
    throw new Error("Either issue_number or discussion_id must be provided");
  }

  // 1. Get the question
  let question: string;
  let questionTitle: string;
  let responseTarget: { type: "issue"; number: number } | { type: "discussion"; id: string };

  if (inputs.issueNumber) {
    const issue = await getIssue(octokit, owner, repo, inputs.issueNumber);
    questionTitle = issue.title;
    question = `${issue.title}\n\n${issue.body ?? ""}`;
    responseTarget = { type: "issue", number: inputs.issueNumber };
  } else {
    const discussionId = inputs.discussionId!;
    const { repository } = await octokit.graphql<{
      repository: {
        discussion: {
          title: string;
          body: string;
          number: number;
        };
      };
    }>(
      `query($owner: String!, $repo: String!, $number: Int!) {
        repository(owner: $owner, name: $repo) {
          discussion(number: $number) {
            title
            body
            number
          }
        }
      }`,
      { owner, repo, number: parseInt(discussionId, 10) },
    );

    questionTitle = repository.discussion.title;
    question = `${repository.discussion.title}\n\n${repository.discussion.body}`;
    responseTarget = { type: "discussion", id: discussionId };
  }

  // 2. Get repository file tree and filter by source_paths
  const defaultBranch = await getDefaultBranch(octokit, owner, repo);
  const tree = await getRepoTree(octokit, owner, repo, defaultBranch.sha);

  const globs = inputs.sourcePaths.split(",").map((s) => s.trim());
  const sourceFiles = tree
    .filter((item) => item.type === "blob")
    .filter((item) => matchesAnyGlob(item.path, globs))
    .map((item) => item.path);

  // 3. Ask Gemini to identify relevant files
  const fileSelectionResponse = await generateContent(model, buildFileSelectionPrompt(question, sourceFiles));
  let relevantFiles: string[];
  try {
    relevantFiles = parseJsonResponse<string[]>(fileSelectionResponse);
    relevantFiles = relevantFiles.filter((f) => sourceFiles.includes(f));
  } catch {
    relevantFiles = sourceFiles.slice(0, 15);
  }

  // 4. Fetch content of relevant files
  const fileContents: Record<string, string> = {};
  for (const filePath of relevantFiles) {
    try {
      const content = await getFileContent(
        octokit,
        owner,
        repo,
        filePath,
        defaultBranch.name,
      );
      fileContents[filePath] = truncateText(content, 5000, filePath);
    } catch {
      // Skip files we can't read
    }
  }

  // 5. Generate answer
  const answer = await generateContent(
    model,
    buildAnswerPrompt(owner, repo, question, fileContents),
  );

  // 6. Post the answer
  const responseBody = `## Answer

${answer}

---
*Based on ${Object.keys(fileContents).length} source file(s) — Generated by [gemini-repo-qa](https://github.com/dortort/gemini-actions)*`;

  if (responseTarget.type === "issue") {
    await postComment(octokit, owner, repo, responseTarget.number, responseBody);
  } else {
    const { repository } = await octokit.graphql<{
      repository: {
        discussion: {
          id: string;
        };
      };
    }>(
      `query($owner: String!, $repo: String!, $number: Int!) {
        repository(owner: $owner, name: $repo) {
          discussion(number: $number) {
            id
          }
        }
      }`,
      { owner, repo, number: parseInt(responseTarget.id, 10) },
    );

    await octokit.graphql(
      `mutation($discussionId: ID!, $body: String!) {
        addDiscussionComment(input: { discussionId: $discussionId, body: $body }) {
          comment {
            id
          }
        }
      }`,
      { discussionId: repository.discussion.id, body: responseBody },
    );
  }
}
