import * as core from "@actions/core";
import {
  generateContent,
  truncateText,
  parseJsonResponse,
  getPullRequest,
  createReview,
  runAction,
  getActionContext,
  ReviewComment,
} from "@gemini-actions/shared";

interface GeminiReviewComment {
  path: string;
  line: number;
  severity: "critical" | "warning" | "suggestion" | "nitpick";
  comment: string;
}

interface GeminiReview {
  summary: string;
  comments: GeminiReviewComment[];
}

const STRICTNESS_PROMPTS: Record<string, string> = {
  low: "Focus only on critical issues: security vulnerabilities, data loss risks, and clear bugs. Ignore style, naming, and minor improvements.",
  medium:
    "Review for bugs, security issues, performance problems, and significant design concerns. Note style issues only if they hurt readability.",
  high: "Perform a thorough review covering bugs, security, performance, design, error handling, edge cases, naming conventions, and code style.",
};

runAction(async () => {
  const prNumber = parseInt(core.getInput("pr_number", { required: true }), 10);
  const strictness = core.getInput("review_strictness") || "medium";

  if (!STRICTNESS_PROMPTS[strictness]) {
    throw new Error(
      `Invalid review_strictness: ${strictness}. Must be low, medium, or high.`,
    );
  }

  const { octokit, owner, repo, model } = getActionContext();

  core.info(`Reviewing PR #${prNumber} with ${strictness} strictness...`);

  // 1. Get PR details and diff
  const pr = await getPullRequest(octokit, owner, repo, prNumber);
  core.info(`PR: ${pr.title} (${pr.files.length} files changed)`);

  // 2. Build the review prompt with truncated diffs
  const maxPatchPerFile = 10000;
  const maxTotalDiff = 200000;

  let totalDiffChars = 0;
  const fileSections: string[] = [];
  for (const f of pr.files) {
    const patch = f.patch ?? "Binary file or no diff available";
    const truncatedPatch = truncateText(patch, maxPatchPerFile, `${f.filename} diff`);
    if (totalDiffChars + truncatedPatch.length > maxTotalDiff) {
      fileSections.push(
        `### ${f.filename} (${f.status}: +${f.additions} -${f.deletions})\n` +
          `*Diff omitted — total diff budget (${(maxTotalDiff / 1000).toFixed(0)}K chars) reached*`,
      );
      continue;
    }
    totalDiffChars += truncatedPatch.length;
    fileSections.push(
      `### ${f.filename} (${f.status}: +${f.additions} -${f.deletions})\n\`\`\`diff\n${truncatedPatch}\n\`\`\``,
    );
  }

  const prompt = `You are an expert code reviewer. Review the following pull request.

**Review Strictness:** ${strictness}
${STRICTNESS_PROMPTS[strictness]}

**PR Title:** ${pr.title}
**PR Description:** ${pr.body ?? "No description provided."}

**Changed Files:**
${fileSections.join("\n\n")}

Provide your review as a JSON object with this structure:
{
  "summary": "Overall review summary in markdown",
  "comments": [
    {
      "path": "filename",
      "line": <line number in the new file>,
      "severity": "critical|warning|suggestion|nitpick",
      "comment": "Your comment"
    }
  ]
}

Guidelines:
- The "line" must be a line number that appears in the diff (within a + or unchanged line)
- Severity levels: critical (must fix), warning (should fix), suggestion (consider), nitpick (optional)
- Be specific and actionable in comments
- Include code examples in suggestions when helpful
- The summary should give an overall assessment and highlight the most important findings

Respond ONLY with the JSON object.`;

  const response = await generateContent(model, prompt);
  let review: GeminiReview;
  try {
    review = parseJsonResponse<GeminiReview>(response);
  } catch {
    // If parsing fails, post the raw response as a comment
    core.warning("Could not parse structured review, posting as plain comment");
    await createReview(
      octokit,
      owner,
      repo,
      prNumber,
      `## Gemini Code Review (${strictness} strictness)\n\n${response}`,
    );
    return;
  }

  // 3. Format and post the review
  const severityEmoji: Record<string, string> = {
    critical: "[CRITICAL]",
    warning: "[WARNING]",
    suggestion: "[SUGGESTION]",
    nitpick: "[NITPICK]",
  };

  const reviewComments: ReviewComment[] = review.comments
    .filter((c) => {
      const fileInPR = pr.files.some((f) => f.filename === c.path);
      if (!fileInPR) {
        core.warning(`Skipping comment for ${c.path}: file not in PR diff`);
      }
      return fileInPR && c.line > 0;
    })
    .map((c) => ({
      path: c.path,
      line: c.line,
      body: `${severityEmoji[c.severity] || ""} ${c.comment}`,
    }));

  const summaryBody = `## Gemini Code Review (${strictness} strictness)

${review.summary}

---
*${review.comments.length} comment(s) across ${new Set(review.comments.map((c) => c.path)).size} file(s) — Generated by [gemini-pr-review](https://github.com/dortort/gemini-actions)*`;

  await createReview(
    octokit,
    owner,
    repo,
    prNumber,
    summaryBody,
    reviewComments,
  );

  core.info(
    `Review posted: ${review.comments.length} comments, ${reviewComments.length} inline`,
  );
});
