import type { PullRequestInfo, ReviewComment } from "@gemini-actions/shared";

export interface GeminiReviewComment {
  path: string;
  line: number;
  severity: "critical" | "warning" | "suggestion" | "nitpick";
  comment: string;
}

export interface GeminiReview {
  summary: string;
  comments: GeminiReviewComment[];
}

const SEVERITY_EMOJI: Record<string, string> = {
  critical: "[CRITICAL]",
  warning: "[WARNING]",
  suggestion: "[SUGGESTION]",
  nitpick: "[NITPICK]",
};

export function filterValidComments(
  comments: GeminiReviewComment[],
  pr: PullRequestInfo,
): ReviewComment[] {
  return comments
    .filter((c) => {
      const fileInPR = pr.files.some((f) => f.filename === c.path);
      return fileInPR && c.line > 0;
    })
    .map((c) => ({
      path: c.path,
      line: c.line,
      body: `${SEVERITY_EMOJI[c.severity] || ""} ${c.comment}`,
    }));
}

export function buildSummaryBody(
  review: GeminiReview,
  strictness: string,
): string {
  return `## Gemini Code Review (${strictness} strictness)

${review.summary}

---
*${review.comments.length} comment(s) across ${new Set(review.comments.map((c) => c.path)).size} file(s) — Generated by [gemini-pr-review](https://github.com/dortort/gemini-actions)*`;
}
