name: "Gemini PR from Issue"
description: "Reads a GitHub issue, analyzes the request using Gemini, generates a code change, and opens a pull request"
author: "dortort"

inputs:
  issue_number:
    description: "The issue number to process"
    required: true
  gemini_api_key:
    description: "Google Gemini API key"
    required: true
  github_token:
    description: "GitHub token with repo write access"
    required: true
  model:
    description: "Gemini model to use"
    required: false
    default: "gemini-2.0-flash"

outputs:
  pr_number:
    description: "The number of the created pull request"

runs:
  using: "node20"
  main: "dist/index.js"
