import type { IssueInfo } from "@gemini-actions/shared";

export function buildPlanPrompt(issue: IssueInfo, fileListText: string): string {
  return `You are a software engineer. A GitHub issue has been filed requesting a change to the repository.

**Issue #${issue.number}: ${issue.title}**
${issue.body ?? "No description provided."}

**Repository files:**
${fileListText}

Analyze the issue and determine which files need to be created or modified to address it.
Respond with a JSON array of file paths that are relevant. Only include files that need changes.
If new files need to be created, include them too.

Respond ONLY with a JSON array of strings, e.g.: ["src/config.ts", "README.md"]`;
}

export function buildChangePrompt(
  issue: IssueInfo,
  fileContents: Record<string, string>,
): string {
  return `You are a software engineer implementing a change based on a GitHub issue.

**Issue #${issue.number}: ${issue.title}**
${issue.body ?? "No description provided."}

**Current file contents:**
${Object.entries(fileContents)
  .map(([path, content]) => `--- ${path} ---\n${content}`)
  .join("\n\n")}

Generate the complete updated file contents for each file that needs to change.
If a file needs to be created, provide its full content.

Respond ONLY with a JSON array of objects with "path" and "content" fields:
[{"path": "src/example.ts", "content": "...full file content..."}]

Important:
- Provide the COMPLETE file content, not just the diff
- Make minimal changes needed to address the issue
- Follow existing code style and conventions`;
}

export function buildPrBody(
  issueNumber: number,
  changes: { path: string }[],
): string {
  return `## Summary

This PR was automatically generated by Gemini to address #${issueNumber}.

### Changes
${changes.map((c) => `- \`${c.path}\``).join("\n")}

### Issue
Closes #${issueNumber}

---
*Generated by [gemini-pr-from-issue](https://github.com/dortort/gemini-actions)*`;
}
