import {
  generateContent,
  truncateText,
  postComment,
  ActionContext,
} from "@gemini-actions/shared";
import type { DatadogClient } from "./datadog";
import { buildAnalysisPrompt, RecentCommit } from "./prompts";

type ActionType = "open_issue" | "comment_on_pr" | "trigger_workflow";

export interface DatadogResponderInputs {
  query: string;
  action: ActionType;
}

export async function runDatadogResponder(
  ctx: ActionContext,
  inputs: DatadogResponderInputs,
  ddClient: DatadogClient,
): Promise<string> {
  const { octokit, owner, repo, model } = ctx;
  const { query, action } = inputs;

  const validActions: ActionType[] = [
    "open_issue",
    "comment_on_pr",
    "trigger_workflow",
  ];
  if (!validActions.includes(action)) {
    throw new Error(
      `Invalid action: ${action}. Must be one of: ${validActions.join(", ")}`,
    );
  }

  // 1. Query Datadog
  let datadogData: string;
  const isMonitorId = /^\d+$/.test(query.trim());

  if (isMonitorId) {
    const monitor = await ddClient.getMonitor(query.trim());
    datadogData = JSON.stringify(monitor, null, 2);
  } else {
    const metrics = await ddClient.queryMetrics(query);
    datadogData = JSON.stringify(metrics, null, 2);
  }

  // 2. Get recent commits for correlation
  const { data: commits } = await octokit.rest.repos.listCommits({
    owner,
    repo,
    per_page: 10,
  });

  const recentCommits: RecentCommit[] = commits.map((c: {
    sha: string;
    commit: { message: string; author: { date?: string; name?: string } | null };
  }) => ({
    sha: c.sha.slice(0, 7),
    message: c.commit.message.split("\n")[0],
    date: c.commit.author?.date,
    author: c.commit.author?.name,
  }));

  // 3. Ask Gemini to interpret the data
  const prompt = buildAnalysisPrompt(
    truncateText(datadogData, 10000, "Datadog data"),
    isMonitorId,
    recentCommits,
    owner,
    repo,
    action,
  );

  const analysis = await generateContent(model, prompt);

  // 4. Take the specified action
  let resultId: string;

  switch (action) {
    case "open_issue": {
      const { data: issue } = await octokit.rest.issues.create({
        owner,
        repo,
        title: `[Datadog Alert] ${isMonitorId ? `Monitor ${query}` : "Metrics anomaly detected"}`,
        body: `## Datadog Alert Analysis\n\n${analysis}\n\n---\n*Generated by [gemini-datadog-responder](https://github.com/dortort/gemini-actions)*`,
        labels: ["datadog", "automated"],
      });
      resultId = issue.number.toString();
      break;
    }

    case "comment_on_pr": {
      const { data: prs } = await octokit.rest.pulls.list({
        owner,
        repo,
        state: "open",
        sort: "updated",
        direction: "desc",
        per_page: 1,
      });

      if (prs.length === 0) {
        throw new Error("No open pull requests found to comment on");
      }

      const prNumber = prs[0].number;
      await postComment(
        octokit,
        owner,
        repo,
        prNumber,
        `## Datadog Alert Analysis\n\n${analysis}\n\n---\n*Generated by [gemini-datadog-responder](https://github.com/dortort/gemini-actions)*`,
      );
      resultId = prNumber.toString();
      break;
    }

    case "trigger_workflow": {
      await octokit.rest.repos.createDispatchEvent({
        owner,
        repo,
        event_type: "datadog-alert",
        client_payload: {
          query,
          analysis,
          is_monitor: isMonitorId,
        },
      });
      resultId = "dispatch-sent";
      break;
    }
  }

  return resultId;
}
