import type { ReviewComment, PullRequestFile } from "@gemini-actions/shared";
import { findDepLineInPatch } from "./parsers";
import type { DependencyAssessment, EnrichedDependencyChange, RiskLevel } from "./types";

const MANIFEST_FILE_RE =
  /(?:^|\/)(package\.json|package-lock\.json|composer\.json|composer\.lock|requirements\.txt|Pipfile|go\.mod|\.terraform\.lock\.hcl)$/;

function isManifestFile(filename: string): boolean {
  return MANIFEST_FILE_RE.test(filename);
}

const riskLabel: Record<RiskLevel, string> = {
  low: "LOW RISK",
  medium: "MEDIUM RISK",
  high: "HIGH RISK",
  critical: "CRITICAL RISK",
};

/**
 * Normalize an LLM-returned risk value to a display label, guarding against
 * case variations (e.g. "Low" vs "low") that parseJsonResponse won't catch.
 */
function safeRiskLabel(risk: unknown): string {
  const normalized = typeof risk === "string" ? (risk.toLowerCase() as RiskLevel) : undefined;
  return (normalized && riskLabel[normalized]) ?? String(risk).toUpperCase();
}

/**
 * Build the review body with a summary table and narrative.
 */
export function buildReviewBody(assessment: DependencyAssessment): string {
  const tableHeader = "| Dependency | Version | Type | Risk | Summary |\n|---|---|---|---|---|";
  const tableRows = assessment.dependencySummaries
    .map(
      (d) =>
        `| ${d.dependency} | ${d.fromVersion} → ${d.toVersion} | ${d.upgradeType} | **${safeRiskLabel(d.risk)}** | ${d.oneLiner} |`,
    )
    .join("\n");

  const actionSection =
    assessment.actionItems.length > 0
      ? `### Action Required\n\n${assessment.actionItems.map((a) => `- **[${a.severity.toUpperCase()}]** \`${a.file}\` — ${a.description}`).join("\n")}\n\n`
      : "";

  return `## Gemini Dependency Impact Analysis

**${safeRiskLabel(assessment.overallRisk)}** — ${assessment.riskJustification}

### Summary

${tableHeader}
${tableRows}

${actionSection}### Details

${assessment.narrativeSummary}

---
*${assessment.dependencySummaries.length} dependency change(s) analyzed — Generated by [gemini-dependency-impact](https://github.com/dortort/gemini-actions)*`;
}

/**
 * Build inline review comments for dependency version-change lines in manifest files.
 */
export function buildInlineComments(
  assessment: DependencyAssessment,
  enrichedDeps: EnrichedDependencyChange[],
  prFiles: PullRequestFile[],
): ReviewComment[] {
  const comments: ReviewComment[] = [];

  for (const annotation of assessment.inlineAnnotations) {
    const dep = enrichedDeps.find((d) => d.name === annotation.dependency);
    if (!dep) continue;

    for (const file of prFiles.filter((f) => isManifestFile(f.filename))) {
      if (!file.patch) continue;
      const line = findDepLineInPatch(file.patch, dep.name);
      if (line != null && line > 0) {
        comments.push({
          path: file.filename,
          line,
          body: annotation.annotation,
        });
        break;
      }
    }
  }

  return comments;
}
